services:
  app:
    build:
      context: .  # 表示当前目录
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"  # 映射容器内的8000端口到宿主机的8000端口
    environment:
      # 这里可以添加你需要的环境变量
      ENV: production
    volumes:
      - .:/app  # 映射当前目录到容器内的/app目录（开发环境可用）
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

